platform :ios, '7.0'

source 'https://github.com/yanghl/seanspec.git'
source 'https://github.com/CocoaPods/Specs.git'

target 'YHLTableView_Example' do
  pod 'YHLTableView', :path => '../'

  target 'YHLTableView_Tests' do
    inherit! :search_paths

#pod 'FBSnapshotTestCase'
  end
end
